language: perl

perl:
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

install:
    - cpanm Dancer Dancer2 DBI --quiet --notest

script:
    - cd Shared;
    - perl Makefile.PL
    - make test
    - make install
    - cd ../Dancer1;
    - perl Makefile.PL
    - make test
    - cd ../Dancer2;
    - perl Makefile.PL
    - make test
